<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_jam extends MY_Model
{

    public $table = 'm_jam';
    public $primary_key = 'jam_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'jam_ke';
        $dataorder[$i++] = 'jam-active';
        if(!empty($this->input->post('jam_ke'))){
            $where['LOWER(jam_ke) LIKE'] = '%'.strtolower($this->input->post('jam_ke')).'%';
        }
        if(!empty($this->input->post('jam-active'))){
            $where['LOWER(jam-active) LIKE'] = '%'.strtolower($this->input->post('jam-active')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($limit, $start);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_jam.php */
/* Location: ./application/models/M_jam.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-28 18:57:26 */
/* http://harviacode.com */