<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_jadwal extends MY_Model
{

    public $table = 't_jadwal';
    public $primary_key = 'jadwal_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'jam_id';
        $dataorder[$i++] = 'hari_id';
        $dataorder[$i++] = 'mapel_id';
        $dataorder[$i++] = 't_kelas_id';
        $dataorder[$i++] = 'jadwal_active';
        $dataorder[$i++] = 'pegawai_id';
        if(!empty($this->input->post('jam_id'))){
            $where['LOWER(jam_id) LIKE'] = '%'.strtolower($this->input->post('jam_id')).'%';
        }
        if(!empty($this->input->post('hari_id'))){
            $where['LOWER(hari_id) LIKE'] = '%'.strtolower($this->input->post('hari_id')).'%';
        }
        if(!empty($this->input->post('mapel_id'))){
            $where['LOWER(mapel_id) LIKE'] = '%'.strtolower($this->input->post('mapel_id')).'%';
        }
        if(!empty($this->input->post('t_kelas_id'))){
            $where['LOWER(t_kelas_id) LIKE'] = '%'.strtolower($this->input->post('t_kelas_id')).'%';
        }
        if(!empty($this->input->post('jadwal_active'))){
            $where['LOWER(jadwal_active) LIKE'] = '%'.strtolower($this->input->post('jadwal_active')).'%';
        }
        if(!empty($this->input->post('pegawai_id'))){
            $where['LOWER(pegawai_id) LIKE'] = '%'.strtolower($this->input->post('pegawai_id')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($start, $limit);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_jadwal.php */
/* Location: ./application/models/M_jadwal.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-31 04:41:58 */
/* http://harviacode.com */