<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_kelas extends MY_Model
{

    public $table = 'm_kelas';
    public $primary_key = 'kelas_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array('kelas_id'); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'kelas_nama';
        $dataorder[$i++] = 'kelas_active';
        if(!empty($this->input->post('kelas_nama'))){
            $where['LOWER(kelas_nama) LIKE'] = '%'.strtolower($this->input->post('kelas_nama')).'%';
        }
        if(!empty($this->input->post('kelas_active'))){
            $where['LOWER(kelas_active) LIKE'] = '%'.strtolower($this->input->post('kelas_active')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($start, $limit);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_kelas.php */
/* Location: ./application/models/M_kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-31 05:24:46 */
/* http://harviacode.com */