<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_menu extends MY_Model
{

    public $table = 'menu';
    public $primary_key = 'id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'name';
        $dataorder[$i++] = 'link';
        $dataorder[$i++] = 'icon';
        $dataorder[$i++] = 'is_active';
        $dataorder[$i++] = 'is_parent';
        if(!empty($this->input->post('name'))){
            $where['LOWER(name) LIKE'] = '%'.strtolower($this->input->post('name')).'%';
        }
        if(!empty($this->input->post('link'))){
            $where['LOWER(link) LIKE'] = '%'.strtolower($this->input->post('link')).'%';
        }
        if(!empty($this->input->post('icon'))){
            $where['LOWER(icon) LIKE'] = '%'.strtolower($this->input->post('icon')).'%';
        }
        if(!empty($this->input->post('is_active'))){
            $where['LOWER(is_active) LIKE'] = '%'.strtolower($this->input->post('is_active')).'%';
        }
        if(!empty($this->input->post('is_parent'))){
            $where['LOWER(is_parent) LIKE'] = '%'.strtolower($this->input->post('is_parent')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($limit, $start);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_menu.php */
/* Location: ./application/models/M_menu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-25 09:21:37 */
/* http://harviacode.com */