<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_siswa extends MY_Model
{

    public $table = 'm_siswa';
    public $primary_key = 'siswa_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'siswa_nis';
        $dataorder[$i++] = 'siswa_nama';
        $dataorder[$i++] = 'siswa_jk';
        $dataorder[$i++] = 'siswa_tgl_lahir';
        $dataorder[$i++] = 'kota_id';
        $dataorder[$i++] = 'kecamatan_id';
        $dataorder[$i++] = 'siswa_alamat';
        $dataorder[$i++] = 'siswa_ayah';
        $dataorder[$i++] = 'siswa_ibu';
        $dataorder[$i++] = 'siswa_wali';
        $dataorder[$i++] = 'telp_ortu';
        if(!empty($this->input->post('siswa_nis'))){
            $where['LOWER(siswa_nis) LIKE'] = '%'.strtolower($this->input->post('siswa_nis')).'%';
        }
        if(!empty($this->input->post('siswa_nama'))){
            $where['LOWER(siswa_nama) LIKE'] = '%'.strtolower($this->input->post('siswa_nama')).'%';
        }
        if(!empty($this->input->post('siswa_jk'))){
            $where['LOWER(siswa_jk) LIKE'] = '%'.strtolower($this->input->post('siswa_jk')).'%';
        }
        if(!empty($this->input->post('siswa_tgl_lahir'))){
            $where['LOWER(siswa_tgl_lahir) LIKE'] = '%'.strtolower($this->input->post('siswa_tgl_lahir')).'%';
        }
        if(!empty($this->input->post('kota_id'))){
            $where['LOWER(kota_id) LIKE'] = '%'.strtolower($this->input->post('kota_id')).'%';
        }
        if(!empty($this->input->post('kecamatan_id'))){
            $where['LOWER(kecamatan_id) LIKE'] = '%'.strtolower($this->input->post('kecamatan_id')).'%';
        }
        if(!empty($this->input->post('siswa_alamat'))){
            $where['LOWER(siswa_alamat) LIKE'] = '%'.strtolower($this->input->post('siswa_alamat')).'%';
        }
        if(!empty($this->input->post('siswa_ayah'))){
            $where['LOWER(siswa_ayah) LIKE'] = '%'.strtolower($this->input->post('siswa_ayah')).'%';
        }
        if(!empty($this->input->post('siswa_ibu'))){
            $where['LOWER(siswa_ibu) LIKE'] = '%'.strtolower($this->input->post('siswa_ibu')).'%';
        }
        if(!empty($this->input->post('siswa_wali'))){
            $where['LOWER(siswa_wali) LIKE'] = '%'.strtolower($this->input->post('siswa_wali')).'%';
        }
        if(!empty($this->input->post('telp_ortu'))){
            $where['LOWER(telp_ortu) LIKE'] = '%'.strtolower($this->input->post('telp_ortu')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($limit, $start);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_siswa.php */
/* Location: ./application/models/M_siswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-26 05:19:48 */
/* http://harviacode.com */