<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_status extends MY_Model
{

    public $table = 'm_status';
    public $primary_key = 'status_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        // $this->soft_deletes = TRUE;
    }
    

}

/* End of file M_siswa.php */
/* Location: ./application/models/M_siswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-25 09:06:23 */
/* http://harviacode.com */