<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_t_absensi extends MY_Model
{

    public $table = 't_absensi';
    public $primary_key = 'absensi_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'jadwal_id';
        $dataorder[$i++] = 't_siswa_id';
        $dataorder[$i++] = 'siswa';
        if(!empty($this->input->post('jadwal_id'))){
            $where['LOWER(jadwal_id) LIKE'] = '%'.strtolower($this->input->post('jadwal_id')).'%';
        }
        if(!empty($this->input->post('t_siswa_id'))){
            $where['LOWER(t_siswa_id) LIKE'] = '%'.strtolower($this->input->post('t_siswa_id')).'%';
        }
        if(!empty($this->input->post('siswa'))){
            $where['LOWER(siswa) LIKE'] = '%'.strtolower($this->input->post('siswa')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($start, $limit);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_t_absensi.php */
/* Location: ./application/models/M_t_absensi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-07 09:31:10 */
/* http://harviacode.com */