<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_t_pegawai extends MY_Model
{

    public $table = 't_pegawai';
    public $primary_key = 't_pegawai_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'pagawai_id';
        $dataorder[$i++] = 'jabatan_id';
        $dataorder[$i++] = 'create_date';
        $dataorder[$i++] = 't_pegawai_active';
        if(!empty($this->input->post('pagawai_id'))){
            $where['LOWER(pagawai_id) LIKE'] = '%'.strtolower($this->input->post('pagawai_id')).'%';
        }
        if(!empty($this->input->post('jabatan_id'))){
            $where['LOWER(jabatan_id) LIKE'] = '%'.strtolower($this->input->post('jabatan_id')).'%';
        }
        if(!empty($this->input->post('create_date'))){
            $where['LOWER(create_date) LIKE'] = '%'.strtolower($this->input->post('create_date')).'%';
        }
        if(!empty($this->input->post('t_pegawai_active'))){
            $where['LOWER(t_pegawai_active) LIKE'] = '%'.strtolower($this->input->post('t_pegawai_active')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($start, $limit);
        $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_t_pegawai.php */
/* Location: ./application/models/M_t_pegawai.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-08 15:58:51 */
/* http://harviacode.com */