<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_t_kelas extends MY_Model
{

    public $table = 't_kelas';
    public $view = 'v_kelas';
    public $primary_key = 't_kelas_id';
    public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array('t_kelas_id'); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        $this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data($limit, $start) {
        $order            = $this->input->post('order');
        $dataorder = array();
        $where = array();

        $i=1;
        
        $dataorder[$i++] = 'kelas_id';
        $dataorder[$i++] = 'jurusan_id';
        $dataorder[$i++] = 'semester_id';
        $dataorder[$i++] = 't_kelas_active';
        $dataorder[$i++] = 'tahun';
        if(!empty($this->input->post('kelas_id'))){
            $where['LOWER(kelas_id) LIKE'] = '%'.strtolower($this->input->post('kelas_id')).'%';
        }
        if(!empty($this->input->post('jurusan_id'))){
            $where['LOWER(jurusan_id) LIKE'] = '%'.strtolower($this->input->post('jurusan_id')).'%';
        }
        if(!empty($this->input->post('semester_id'))){
            $where['LOWER(semester_id) LIKE'] = '%'.strtolower($this->input->post('semester_id')).'%';
        }
        if(!empty($this->input->post('t_kelas_active'))){
            $where['LOWER(t_kelas_active) LIKE'] = '%'.strtolower($this->input->post('t_kelas_active')).'%';
        }
        if(!empty($this->input->post('tahun'))){
            $where['LOWER(tahun) LIKE'] = '%'.strtolower($this->input->post('tahun')).'%';
        }
        $this->where($where);
        $result['total_rows'] = $this->count_rows();
        
        $this->where($where);
        $this->order_by( $dataorder[$order[0]["column"]],  $order[0]["dir"]);
        $this->limit($start, $limit);
        $result['get_db']= $this->db->get($this->view)->result_array();
        // $result['get_db']=$this->as_array()->get_all();
        return $result;
    }

}

/* End of file M_t_kelas.php */
/* Location: ./application/models/M_t_kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-31 05:28:03 */
/* http://harviacode.com */