<?php 

$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class " . $m . " extends MY_Model
{

    public \$table = '$table_name';
    public \$primary_key = '$pk';
    public \$fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public \$protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

    function __construct()
    {
        parent::__construct();
        \$this->soft_deletes = TRUE;
    }
    
    // get total rows
    function get_limit_data(\$limit, \$start) {
        \$order            = \$this->input->post('order');
        \$dataorder = array();
        \$where = array();

        \$i=1;
        ";
foreach ($non_pk as $row) {
    $string .= "
        \$dataorder[\$i++] = '". $row['column_name'] ."';";
}
foreach ($non_pk as $row) {
    $string .= "
        if(!empty(\$this->input->post('" . $row['column_name'] ."'))){
            \$where['LOWER(" . $row['column_name'] .") LIKE'] = '%'.strtolower(\$this->input->post('" . $row['column_name'] ."')).'%';
        }";
}    

$string .= "
        \$this->where(\$where);
        \$result['total_rows'] = \$this->count_rows();
        
        \$this->where(\$where);
        \$this->order_by( \$dataorder[\$order[0][\"column\"]],  \$order[0][\"dir\"]);
        \$this->limit(\$limit, \$start);
        \$result['get_db']=\$this->as_array()->get_all();
        return \$result;
    }

}

/* End of file $m_file */
/* Location: ./application/models/$m_file */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
/* http://harviacode.com */";




$hasil_model = createFile($string, $target."models/" . $m_file);

?>